In [57]:
import numpy as np

In [58]:
class Graph:
    matrix = []
    lists = {}

    def __init__(self, vertices):
        self.vertices = vertices
        Graph.matrix = np.zeros((vertices, vertices), dtype = int)

    def add_vertex(self, start, end, weight):
        Graph.matrix[start][end] = weight

    def BFS(self, start):
        start = start - 1
        visited = [False] * self.vertices
        queue = [start]

        visited[start] = True

        while queue:
            vis = queue[0]

            print(vis + 1, end = ' ')
            queue.pop(0)

            for i in range(self.vertices):
                if (Graph.matrix[vis][i] != 0) and (not visited[i]):
                    queue.append(i)

                    visited[i] = True

    def print_matrix(self):
        print(Graph.matrix)

In [59]:
vertices = int(input('Insert the number of nodes: '))
g = Graph(vertices)
print('The graph vertices:', g.vertices)

The graph vertices: 4


In [60]:
for i in range(g.vertices):
    for j in range(g.vertices):
        if (i != j):
            weight = int(input(f'Insert the edge weight from vertex {i + 1} to {j + 1}: '))
            
            g.add_vertex(i, j, int(weight))

print('The adjacency matrix:')
g.print_matrix()

The adjacency matrix:
[[0 1 1 0]
 [1 0 0 1]
 [1 0 0 0]
 [0 1 0 0]]


In [65]:
start = int(input('Start the BFS traversal from vertex: '))
print('The BFS traversal:')
g.BFS(start)

The BFS traversal:
4 2 1 3 