### Import Library

In [1]:
# numpy used to make zero matrix
import numpy as np

### Create Graph Class
Graph class used to manage the adjacency matrix and list from a graph.

In [2]:
class Graph:
    # empty matrix (list) and list (dictionary)
    matrix = []
    lists = {}

    # constructor method to register the vertices
    def __init__(self, vertices):
        self.vertices = vertices
        # create zero matrix for adjacency matrix
        Graph.matrix = np.zeros((vertices, vertices), dtype = int)\
        # create empty dictionary for adjacency list
        for i in range(vertices):
            Graph.lists[i + 1] = []

    # method to add the vertices and its edge weight
    def add_vertex(self, start, end, weight):
        Graph.matrix[start][end] = weight

    # method to create adjacency list from the adjacency matrix that has been made
    def create_list(self):
        # loop the matrix's row
        for i in range(self.vertices):
            # loop the matrix's column
            for j in range(self.vertices):
                # if there's any edge (the weight more than 0)
                if self.matrix[i][j] != 0:
                    # create list based the current vertex
                    self.lists[i + 1].append((j + 1, self.matrix[i][j]))

    # method for BFS traversal
    def BFS(self, start):
        # starting point (root) of traversal
        start = start - 1
        # create visited list to mark the visited vertex (false == not visited)
        visited = [False] * self.vertices
        # create queue and enqueue the first vertex
        queue = [start]

        # mark the first vertex as visited
        visited[start] = True

        # while the queue not empty
        while queue:
            # take the first element of queue as the current visited vertex
            vis = queue[0]

            # print the visited vertex
            print(vis + 1, end = ' ')
            # dequeue the visited vertex
            queue.pop(0)

            # traverse the vertex connected with the current visited vertex
            for i in range(self.vertices):
                # if there's a vertex connected (weight more than 0) and not visited yet
                if (Graph.matrix[vis][i] != 0) and (not visited[i]):
                    # enqueue it to the queue
                    queue.append(i)

                    # and mark the enqueued vertex as visited
                    visited[i] = True

    # method for DFS traversal
    def DFS(self, start, visited):
        # print the starting point vertex (root) first
        print(start + 1, end = ' ')
        # mark the 'start' vertex as visited
        visited[start] = True

        # traverse the vertex connected with the current visited vertex
        for i in range(self.vertices):
            # if there's a vertex connected (weight more than 0) and not visited yet
            if (Graph.matrix[start][i] != 0) and (not visited[i]):
                # call the DFS method to do recursive and use the current vertex as root
                self.DFS(i, visited)

    # method to print the adjacency matrix
    def print_matrix(self):
        print(Graph.matrix)

    # method to print the adjacency list
    def print_list(self):
        self.create_list()
        for l in self.lists:
            print(l, ': ', self.lists[l])

### Insert the Informations of A Graph

In [3]:
# insert the number of vertices of a user's graph
vertices = int(input('Insert the number of vertices: '))
# create a graph object with n vertices
g = Graph(vertices)
# show the number of graph's vertices
print('The graph vertices:', g.vertices)

The graph vertices: 7


In [6]:
# make loop for the matrix's row
for i in range(g.vertices):
    # make loop for the matrix's column
    for j in range(g.vertices):
        # if the row and column index not equal (not in diagonal)
        if (i != j):
            # insert the weight of an edge that connect 2 vertex
            weight = int(input(f'Insert the edge weight from vertex {i + 1} to {j + 1}: '))
            
            # add the vertex and weight to the graph object
            g.add_vertex(i, j, int(weight))

# show the adjacency matrix
print('The adjacency matrix:')
g.print_matrix()

# show the adjacency list
print('\nThe adjacency list:')
g.print_list()

The adjacency matrix:
[[ 0  3  0  0  0 12  0]
 [ 3  0  5  0  0  0  4]
 [ 0  5  0  6  0  0  3]
 [ 0  0  6  0  1  0  0]
 [ 0  0  0  1  0 10  7]
 [12  0  0  0 10  0  2]
 [ 0  4  3  0  7  2  0]]

The adjacency list:
1 :  [(2, 3), (6, 12)]
2 :  [(1, 3), (3, 5), (7, 4)]
3 :  [(2, 5), (4, 6), (7, 3)]
4 :  [(3, 6), (5, 1)]
5 :  [(4, 1), (6, 10), (7, 7)]
6 :  [(1, 12), (5, 10), (7, 2)]
7 :  [(2, 4), (3, 3), (5, 7), (6, 2)]


### The BFS and DFS Traversal

In [7]:
# insert the starting point of traversal
start = int(input('Start the BFS traversal from vertex: '))
# show the BFS traversal
print('The BFS traversal:')
g.BFS(start)

The BFS traversal:
1 2 6 3 7 5 4 

In [8]:
# insert the starting point of traversal
start = int(input('Start the DFS traversal from vertex: '))
# show the DFS traversal
print('The DFS traversal:')
g.DFS(start - 1, [False] * g.vertices)

The DFS traversal:
1 2 3 4 5 6 7 